/**
 * Evidence delivery off-path golden: with `return_unit` omitted (or `chunk`,
 * explicit or from config) search, query, recall, think's prompt and the MCP
 * serialization are byte-identical to the pre-feature release.
 *
 * Authoring gate: protects the frozen off-path contract (plan amendment 6).
 * Regression: any stage/param/meta change that leaks into default responses
 * (a `delivery` key, a changed result count, recall field order, think
 * excerpting). The fixture was generated by this same file on the release
 * before evidence delivery (refactor wave 1, 9a0e01b4) and must not be
 * regenerated on a branch that changes the off path.
 *
 * The Postgres arm lives in test/e2e/evidence-delivery-parity.test.ts.
 */
import { afterAll, beforeAll, describe, expect, test } from 'bun:test';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { PGLiteEngine } from '../src/core/pglite-engine.ts';
import { captureOffPath, seedOffPath } from './helpers/evidence-delivery-fixture.ts';

const FIXTURE = join(import.meta.dir, 'fixtures/goldens/evidence-delivery/off-path.json');
let engine: PGLiteEngine;

beforeAll(async () => {
  engine = new PGLiteEngine();
  await engine.connect({});
  await engine.initSchema();
  await seedOffPath(engine);
}, 240_000);

afterAll(async () => {
  await engine.disconnect();
}, 240_000);

describe('evidence delivery off path', () => {
  test('omitted / chunk return_unit is byte-identical to the pre-feature release', async () => {
    const got = await captureOffPath(engine);
    if (process.env.GBRAIN_TEST_UPDATE_GOLDENS === '1') {
      mkdirSync(dirname(FIXTURE), { recursive: true });
      writeFileSync(FIXTURE, JSON.stringify(got, null, 2) + '\n');
    }
    const want = JSON.parse(readFileSync(FIXTURE, 'utf8')) as Record<string, string>;
    expect(Object.keys(got).sort()).toEqual(Object.keys(want).sort());
    for (const key of Object.keys(want)) expect(`${key}: ${got[key]}`).toBe(`${key}: ${want[key]}`);
  });

  test('a config-level chunk unit is also byte-identical', async () => {
    const want = JSON.parse(readFileSync(FIXTURE, 'utf8')) as Record<string, string>;
    await engine.setConfig('search.return_unit', 'chunk');
    await engine.setConfig('think.return_unit', 'chunk');
    try {
      const got = await captureOffPath(engine);
      for (const key of Object.keys(want)) expect(`${key}: ${got[key]}`).toBe(`${key}: ${want[key]}`);
    } finally {
      await engine.executeRaw(`DELETE FROM config WHERE key IN ('search.return_unit', 'think.return_unit')`);
    }
  });
});
