self-hosted-runner:
  labels:
    - ubicloud-standard-2-ubuntu-2404
    - ubicloud-standard-4-ubuntu-2404
    - ubicloud-standard-16-ubuntu-2404
    - ubicloud-standard-30-ubuntu-2404
    - ubicloud-standard-16-arm-ubuntu-2404
