import { SHARED_SKILLS_SCHEMA_STATEMENTS, SHARED_SKILLS_DELIVERY_LEASE_SCHEMA_STATEMENTS } from './schema.ts';
import { SHARED_SKILLS_MEMBERSHIP_SCHEMA_STATEMENTS } from './membership-schema.ts';
import { SHARED_SKILLS_PERSISTENCE_SCHEMA_STATEMENTS, SHARED_SKILLS_PUBLICATION_GUARD_STATEMENTS } from './persistence-schema.ts';
import { SHARED_SKILLS_ACCESS_SCHEMA_SQL } from './access-schema.ts';

export const SHARED_SKILLS_SCHEMA_SQL = [
  ...SHARED_SKILLS_SCHEMA_STATEMENTS,
  ...SHARED_SKILLS_MEMBERSHIP_SCHEMA_STATEMENTS,
  ...SHARED_SKILLS_PERSISTENCE_SCHEMA_STATEMENTS,
  ...SHARED_SKILLS_PUBLICATION_GUARD_STATEMENTS,
  ...SHARED_SKILLS_DELIVERY_LEASE_SCHEMA_STATEMENTS,
].join(';\n') + ';\n' + SHARED_SKILLS_ACCESS_SCHEMA_SQL;
